// CocoaTrack V2 - Type Definitions
// This file exports all shared types

// Re-export database types (generated by Supabase CLI)
export * from './database.gen';

// Re-export parcelles module types (excluding types that conflict with database.gen)
export {
  // Enums and Constants
  CONFORMITY_STATUS_VALUES,
  type ConformityStatus,
  CONFORMITY_STATUS_LABELS,
  CONFORMITY_STATUS_COLORS,
  PARCELLE_SOURCE_VALUES,
  type ParcelleSource,
  PARCELLE_SOURCE_LABELS,
  CERTIFICATIONS_WHITELIST,
  type Certification,
  CERTIFICATION_LABELS,
  getCertificationsWhitelistSQL,
  // Risk Flags
  type DeforestationRisk,
  type ZoneProtegeeRisk,
  type OverlapRisk,
  type RiskFlags,
  // Centroid
  type Centroid,
  // Planteur relation
  type PlanteurRelation,
  // Parcelle interfaces (use database.gen.ts Parcelle for DB row type)
  type ParcelleWithPlanteur,
  // Import types
  type ImportFileType,
  type ImportStatus,
  type ParseError,
  type ParseWarning,
  type ParseReport,
  type FieldMapping,
  type FeatureValidation,
  type ParsedFeature,
  // Filters
  type ParcelleFilters,
  type ParsedBBox,
  // API Input types
  type CreateParcelleInput,
  type UpdateParcelleInput,
  type ImportDefaults,
  type ApplyImportInput,
  // API Output types
  type ApplyImportResult,
  type ParseResult,
  type ExportFormat,
  type ExportParams,
  // Error types
  PARCELLE_ERROR_CODES,
  type ParcelleErrorCode,
  type ParcelleApiError,
  type ShapefileMissingRequiredDetails,
  type InvalidGeometryDetails,
  type UnsupportedGeometryTypeDetails,
  type LikelyProjectedCoordinatesDetails,
  type LimitExceededDetails,
  type DuplicateFileDetails,
  type ValidationErrorDetails,
  // Response types
  type ParcelleListResponse,
  type ParcelleKPIs,
  type ImportFileListResponse,
  // Limits
  PARCELLE_LIMITS,
} from './parcelles';

// Re-export validation types (only the ones that don't conflict with database.gen)
export type {
  // Planteur validations
  CreatePlanteurInput,
  UpdatePlanteurInput,
  PlanteurFilters,
  PlanteurSearch,
  PlanteurStats,
  PlanteurWithRelations,
  // Chef Planteur validations
  CreateChefPlanteurInput,
  UpdateChefPlanteurInput,
  ValidateChefPlanteurInput,
  RejectChefPlanteurInput,
  ChefPlanteurFilters,
  ChefPlanteurSearch,
  ChefPlanteurStats,
  ChefPlanteurWithRelations,
  ValidationHistoryEntry,
  // Delivery validations
  CreateDeliveryInput,
  UpdateDeliveryInput,
  DeliveryFilters,
  DeliveryWithRelations,
  // Invoice validations
  CreateInvoiceInput,
  InvoiceFilters,
  InvoiceWithRelations,
} from '../lib/validations';

// Re-export validation schemas
export {
  // Planteur schemas
  planteurSchema,
  createPlanteurSchema,
  updatePlanteurSchema,
  planteurFiltersSchema,
  planteurSearchSchema,
  planteurWithRelationsSchema,
  planteurStatsSchema,
  // Chef Planteur schemas
  chefPlanteurSchema,
  createChefPlanteurSchema,
  updateChefPlanteurSchema,
  validateChefPlanteurSchema,
  rejectChefPlanteurSchema,
  chefPlanteurFiltersSchema,
  chefPlanteurSearchSchema,
  chefPlanteurWithRelationsSchema,
  chefPlanteurStatsSchema,
  validationHistoryEntrySchema,
  // Delivery schemas
  createDeliverySchema,
  updateDeliverySchema,
  deliveryFiltersSchema,
  // Invoice schemas
  createInvoiceSchema,
  invoiceFiltersSchema,
  // Common schemas
  paginationSchema,
} from '../lib/validations';

// User and Auth types
// Note: 'agent' is kept for backward compatibility with existing database records
export type UserRole = 'admin' | 'manager' | 'agent' | 'viewer';

export interface User {
  id: string;
  email: string;
  full_name: string;
  role: UserRole;
  cooperative_id: string | null;
  region_id: string | null;
  phone: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

// Validation status
export type ValidationStatus = 'pending' | 'validated' | 'rejected';

// Quality grades
export type QualityGrade = 'A' | 'B' | 'C';

// Payment status
export type PaymentStatus = 'pending' | 'partial' | 'paid';

// Invoice status
export type InvoiceStatus = 'draft' | 'sent' | 'paid';

// Pagination
export interface PaginationParams {
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

export interface PaginatedResult<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

// API Response types
export interface ApiResponse<T> {
  data: T | null;
  error: ApiError | null;
}

export interface ApiError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}

// Sync operation types
export type SyncOperationType = 'CREATE' | 'UPDATE' | 'DELETE';
export type SyncStatus = 'pending' | 'syncing' | 'synced' | 'failed' | 'needs_review' | 'pending_auth';
export type OperationPriority = 'critical' | 'high' | 'normal' | 'low';

export interface SyncOperation {
  id: string;
  idempotency_key: string;
  type: SyncOperationType;
  table: string;
  record_id: string;
  client_id: string;          // UUID generated client-side for offline entities
  server_id: string | null;   // null until synced
  user_id: string;            // CRITICAL: for cross-user isolation
  cooperative_id: string;     // CRITICAL: for cross-coop isolation
  data: Record<string, unknown>;
  base_snapshot: Record<string, unknown> | null;
  base_updated_at: string | null;
  row_version: number | null; // For optimistic concurrency (server)
  priority: OperationPriority;
  created_at: string;
  status: SyncStatus;
  error?: string;
  retry_count: number;
  conflict_info?: SyncConflictInfo | null; // Conflict details when status is 'needs_review'
}

/**
 * Conflict information stored with a sync operation
 * REQ-SYNC-003, REQ-SYNC-007
 */
export interface SyncConflictInfo {
  operation_id: string;
  table: string;
  record_id: string;
  local_version: number | null;
  server_version: number;
  server_updated_at: string;
  server_updated_by: string;
  fields_changed: SyncFieldConflict[];
  detected_at: string;
}

/**
 * Individual field conflict details
 */
export interface SyncFieldConflict {
  field: string;
  local_value: unknown;
  server_value: unknown;
  is_critical: boolean;
}


// Extended database types for tables not in generated types
// These are used when the Supabase CLI doesn't generate types for certain tables/functions

// Extended Planteur type with new fields for parcelles import evolution
// These fields are added by migration 20250110000003_planteurs_name_norm.sql
// but may not be in database.gen.ts until regenerated
export interface PlanteurExtended {
  id: string;
  name: string;
  name_norm: string; // Normalized name (lower, trim, unaccent) for matching
  code: string;
  cooperative_id: string;
  chef_planteur_id: string;
  auto_created: boolean; // True if created automatically during import
  created_via_import_id: string | null; // Reference to the import file that created this planteur
  cni: string | null;
  phone: string | null;
  region: string | null;
  departement: string | null;
  localite: string | null;
  latitude: number | null;
  longitude: number | null;
  superficie_hectares: number | null;
  statut_plantation: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  created_by: string;
}

// Type for creating a planteur with the new fields
export interface CreatePlanteurExtendedInput {
  name: string;
  code: string;
  cooperative_id: string;
  chef_planteur_id: string;
  auto_created?: boolean;
  created_via_import_id?: string | null;
  cni?: string | null;
  phone?: string | null;
  region?: string | null;
  departement?: string | null;
  localite?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  superficie_hectares?: number | null;
  statut_plantation?: string | null;
}

export interface InvoiceDeliveryRow {
  id: string;
  invoice_id: string;
  delivery_id: string;
  created_at: string;
}

export interface SyncOperationRow {
  id: string;
  idempotency_key: string;
  table_name: string;
  operation: 'CREATE' | 'UPDATE' | 'DELETE';
  record_id: string;
  data: Record<string, unknown>;
  status: SyncStatus;
  error_message: string | null;
  retry_count: number;
  created_at: string;
  updated_at: string;
}

// RPC function argument types
export interface GetAuditLogsArgs {
  p_table_name: string | null;
  p_row_id: string | null;
  p_actor_id: string | null;
  p_action: string | null;
  p_start_date: string | null;
  p_end_date: string | null;
  p_limit: number;
  p_offset: number;
}

export interface CountAuditLogsArgs {
  p_table_name: string | null;
  p_row_id: string | null;
  p_actor_id: string | null;
  p_action: string | null;
  p_start_date: string | null;
  p_end_date: string | null;
}

export interface ValidateChefPlanteurArgs {
  p_chef_planteur_id: string;
}

export interface RejectChefPlanteurArgs {
  p_chef_planteur_id: string;
  p_rejection_reason: string;
}

export interface SyncOperationArgs {
  p_idempotency_key: string;
  p_table: string;
  p_operation: 'CREATE' | 'UPDATE' | 'DELETE';
  p_record_id: string;
  p_data: Record<string, unknown>;
}
